
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vckwwisktamiieddnahp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZja3d3aXNrdGFtaWllZGRuYWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzc1MzIsImV4cCI6MjA2MzgxMzUzMn0.mHgDkYRuYxAZnuGG0EQnmR1v_zbAVyusOhEqZrFWo7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
